export const Questions5 = [
    {
        question : 'What is the primary characteristic of an educated man in traditional African education according to Fafunwa?',
        optionA: 'Scholar',
        optionB: 'Warrior, hunter, nobleman, and a man of character',
        optionC: 'Artist',
        optionD: 'Businessman',
        answer: 'B',
    },
    {
        question : 'According to Fafunwa, what is the guiding principle of African education?',
        optionA: 'Intellectualism',
        optionB: 'Functionalism',
        optionC: 'Formalism',
        optionD: 'Vocationalism',
        answer: 'B',
    },
    {
        question : 'At what stage does traditional education generally begin in African societies?',
        optionA: 'At school',
        optionB: 'In the community',
        optionC: 'At home',
        optionD: 'In religious institutions',
        answer: 'C',
    },
    {
        question : 'Which level of traditional African education is comparable to the primary level of formal education?',
        optionA: 'Secret societies',
        optionB: 'Neighbourhood education',
        optionC: 'Community education',
        optionD: 'Home education',
        answer: 'D',
    },
    {
        question : 'Which of the following is NOT one of the identified objectives of traditional African education?',
        optionA: 'To develop physical skills',
        optionB: 'To acquire specific vocational training',
        optionC: 'To develop intellectual skills',
        optionD: 'To acquire modern technological skills',
        answer: 'D',
    },
    {
        question : 'What is considered the primary objective of traditional education in Nigeria?',
        optionA: 'Financial success',
        optionB: 'Character training',
        optionC: ' Political participation',
        optionD: 'Academic excellence',
        answer: 'B',
    },
    {
        question : 'How are children expected to show respect to elders during meals in traditional Nigerian education?',
        optionA: 'By speaking only when spoken to',
        optionB: 'By not taking the first piece of meat',
        optionC: 'By serving food to everyone',
        optionD: 'By eating quietly without speaking',
        answer: 'B',
    },
    {
        question : 'Which proverb illustrates the importance of traditional education in Africa according to the passage?',
        optionA: '"A child who is not intelligent will not survive."',
        optionB: '"A child is a reflection of the parents."',
        optionC: '"Education is the key to success."',
        optionD: '"A child learns by watching."',
        answer: 'A',
    },
    {
        question : 'Which level of African traditional education involves learning from secret societies?',
        optionA: 'Primary level',
        optionB: 'Secondary level',
        optionC: 'Community level',
        optionD: 'Higher level',
        answer: 'D',
    },
    {
        question : 'What method of learning is emphasized in traditional African education for intellectual development?',
        optionA: 'Memorization',
        optionB: 'Observation and imitation',
        optionC: ' Formal classroom teaching',
        optionD: 'Textbook study',
        answer: 'B',
    },
    {
        question : 'What is a common method for teaching numeracy in traditional Nigerian education?        ',
        optionA: 'Using calculators',
        optionB: 'Playing numerical games',
        optionC: 'Attending formal schools',
        optionD: 'Reading textbooks',
        answer: 'B',
    },
    {
        question : 'In the context of traditional education, what is the role of the extended family?',
        optionA: 'To provide financial support',
        optionB: 'To teach formal subjects',
        optionC: 'To participate in the child’s upbringing and education',
        optionD: 'To provide healthcare',
        answer: 'C',
    },
    {
        question : 'Which of the following traditional vocations is NOT mentioned in the text?',
        optionA: 'Carving',
        optionB: 'Drumming',
        optionC: 'Computer programming',
        optionD: 'Hunting',
        answer: 'C',
    },
    {
        question : 'How does traditional education compare to modern formal education according to Babarinde?',
        optionA: 'It is less structured but still comparable',
        optionB: 'It is more advanced',
        optionC: 'It focuses only on practical skills',
        optionD: 'It is identical in structure',
        answer: 'A',
    },
    {
        question : 'What is a key feature of traditional education that is distinct from formal education?',
        optionA: 'Structured curriculum',
        optionB: 'Use of textbooks',
        optionC: 'Informal and practical learning',
        optionD: 'Standardized testing',
        answer: 'C',
    },
    {
        question : 'In traditional Nigerian education, who is primarily responsible for the early rearing and education of a child?',
        optionA: ' The father',
        optionB: 'The mother',
        optionC: 'The community',
        optionD: 'The teacher',
        answer: 'B',
    },
    {
        question : 'What is one reason why parents might send their children to serve as apprentices with friends rather than under themselves?',
        optionA: 'To avoid conflicts of interest',
        optionB: 'To ensure strict discipline',
        optionC: 'To provide additional family support',
        optionD: 'To offer more relaxed learning environments',
        answer: 'B',
    },
    {
        question : 'Which societal change has negatively impacted traditional education according to the passage?',
        optionA: 'Increased emphasis on respect',
        optionB: 'Introduction of modern technology and foreign cultures',
        optionC: 'Strengthening of traditional ceremonies',
        optionD: ' Increase in oral storytelling',
        answer: 'B',
    },
    {
        question : 'What aspect of traditional education is mentioned as declining due to western influence?',
        optionA: 'The use of proverbs',
        optionB: 'The practice of traditional ceremonies',
        optionC: 'The mother tongue',
        optionD: 'The focus on community involvement',
        answer: 'C',
    },
    {
        question : 'How has the role of children in traditional societies changed in the modern era?',
        optionA: 'Children are more obedient and less challenging',
        optionB: 'Children are less involved in family activities',
        optionC: 'Children are more inquisitive and challenging',
        optionD: 'Children have less access to modern technology',
        answer: 'C',
    }
]